### ISSUE TITLE
No text selected

### ISSUE THREAD

**Issue by ashdelta1023** [theJayTea/WritingTools#3]
Every time I use the program, i get a popup saying "No text selected". The program will still function correctly if I close this popup and continue with my selection. 
![Screenshot 2024-10-16 151102](https://github.com/user-attachments/assets/285c08ba-787e-4680-afa0-f40ddf25e79f)

**Comment by ssobii2** [comment]
For me it does not show the popup even and just says no text selected :(

**Comment by ashdelta1023** [comment]
Text is deleted if you try using the shortcut in the windows phone link app for messaging aswell

**Comment by theJayTea** [comment]
Thanks so much for the bug reports! Evidently, it seems to not work perfectly on some devices. I'll investigate these as soon as I get time.

1. Did restarting Writing Tools fix your issues? (This could fix issues with the wonky keyboard hotkey registration API, etc.)

2. If you still face issues after restarting Writing Tools, would you be able to run it from the main.py file with `python main.py`, and share the last logs on the terminal when you face the issue? 
The compiled exe has logging stripped.

**Comment by ssobii2** [comment]
> Thanks so much for the bug reports! Evidently, it seems to not work perfectly on some devices. I'll investigate these as soon as I get time.
> 
> 1. Did restarting Writing Tools fix your issues? (This could fix issues with the sometimes wonky keyboard hotkey registration library, etc.)
> 2. If you still face issues after restarting Writing Tools, would you be able to run it from the main.py file with `python main.py`, and share the last logs on the terminal when you face the issue?
>    The compiled exe has logging stripped.

For me the text is removed when I use ctrl + space as well and it says No text detected. I changed the hotkey to something else which does not remove the text but it still says No text detected.

**Comment by XahidX** [comment]
> It doesn't show the popup and just says "no text selected" for me.

Same for me,
Worked 1st time, but then "no text selected" all the time. 

& Thanks for great sharing.

**Comment by deroverda** [comment]
I had the same issue until a couple of seconds ago. I have no idea if these exacts step made the popup saying "No text selected" disappear, but this is what I did (win 10 user) 

1. Run "Writing Tools.exe" as administrator.
2. Change hotkeys to "ctrl+alt+a", save, and quit.
3. Reopen as administrator, change back to "ctrl+space", and quit.
4. Open normally. The popup should be gone.

**Comment by ssobii2** [comment]
> I had the same issue until a couple of seconds ago. I have no idea if these exacts step made the popup saying "No text selected" disappear, but this is what I did (win 10 user)
> 
> 1. Run "Writing Tools.exe" as administrator.
> 2. Change hotkeys to "ctrl+alt+a", save, and quit.
> 3. Reopen as administrator, change back to "ctrl+space", and quit.
> 4. Open normally. The popup should be gone.

Will try it and share it if it works

**Comment by ssobii2** [comment]
> > It doesn't show the popup and just says "no text selected" for me.
> 
> Same for me, Worked 1st time, but then "no text selected" all the time.
> 
> & Thanks for great sharing.

It didn’t even worked for me first time 😅

**Comment by muzakkir87** [comment]
> I had the same issue until a couple of seconds ago. I have no idea if these exacts step made the popup saying "No text selected" disappear, but this is what I did (win 10 user)
> 
> 1. Run "Writing Tools.exe" as administrator.
> 2. Change hotkeys to "ctrl+alt+a", save, and quit.
> 3. Reopen as administrator, change back to "ctrl+space", and quit.
> 4. Open normally. The popup should be gone.

Thanks, Its work for me..

**Comment by theJayTea** [comment]
I'm glad you were able to fix it for now. I'm still investigating this rare bug.

Restarting writing tools (close them with Task Manager and launch them again) may fix issues such as these.

**Comment by theJayTea** [comment]
@XahidX @ssobii2 Run it as administrator, set the shortcut key to `ctrl+j`, and relaunch it for this to take effect. 
It should then work. 
On a few devices, for some reason, Writing Tools isn't properly able to intercept `ctrl+space` (maybe because of other apps in the background also registering their own similar hotkeys?), and it leads to the issue you're facing.

**Comment by ssobii2** [comment]
> @XahidX @ssobii2 Run it as administrator, set the shortcut key to `ctrl+j`, and relaunch it for this to take effect. It should then work. On a few devices, for some reason, Writing Tools isn't properly able to intercept `ctrl+space` (maybe because of other apps in the background also registering their own similar hotkeys?), and it leads to the issue you're facing.

Will try and let you know :)

**Comment by theJayTea** [comment]
@ssobii2 I'm glad that worked!

The issue is that if an existing app already uses a shortcut key, Writing Tools can't intercept it, sadly. This is something I look to improve in the future with a better hotkey binding and detection API.

You could also try **Ctrl+`** (the key under escape) :)

**Comment by XahidX** [comment]
> @XahidX @ssobii2 Run it as administrator, set the shortcut key to `ctrl+j`, and relaunch it for this to take effect. It should then work. On a few devices, for some reason, Writing Tools isn't properly able to intercept `ctrl+space` (maybe because of other apps in the background also registering their own similar hotkeys?), and it leads to the issue you're facing.

Thanks,
It works after the shortcut key Ctrl + j
other shortcut bring the menu box (enter the instruction)

**Comment by ssobii2** [comment]
> @ssobii2 I'm glad that worked!
> 
> The issue is that if an existing app already uses a shortcut key, Writing Tools can't intercept it, sadly. This is something I look to improve in the future with a better hotkey binding and detection API.
> 
> You could also try **Ctrl+`** (the key under escape) :)

Thanks will try ctrl + ‘ I know the key because ctrl + j still sometimes does not work.

**Comment by kacnje** [comment]
I don't know how to change "shortcut key". I ran the program as an administrator, went to settings and tried to change "shortcut key" (because the original combo didn't work). 
But I don't know how to change it. I click into the field, tried with different combination, but it didn't write my combo. The fiels remained empty (or sometimes only a character appered).

**Comment by theJayTea** [comment]
@kacnje you'll have to type out the shortcut key haha.

Just paste in:
ctrl+`
(or)
ctrl+j

Only a few shortcut keys work as many of them are already in use by apps, background processses, or the OS, in which case writing tools can't reliably intercept them. The above 2 should work, though.

**Comment by kacnje** [comment]
I would have never guessed that. :-)

Back to the issue - I must report that this doesn't work. 
If I select the text and press Ctrl+J, it recognizes the shortcut, DELETES all text, and opens this dialog:
![2024-10-21_10-52](https://github.com/user-attachments/assets/9fa1c4fc-4b92-423c-882f-2c18014c203d)

**Comment by arsaboo** [comment]
I am seeing the same @kacnje with the CTRL + ` shortcut in Word. It does not delete the text but just opens that empty dialog. It works fine in Notepad.

**Comment by arsaboo** [comment]
@theJayTea Please note that CTRL+J is the keyboard shortcut to justify text in MS Word, so that may not be ideal. CTRL+` may be a better choice. Irrespective, I cannot get it to work on MS Word.

**Comment by theJayTea** [comment]
Hey @arsaboo , I have great news for you. I've fixed the issue that prevented it from working in MS Word :)
I will push this update out by tomorrow.

**Comment by theJayTea** [comment]
@kacnje , there is a new keyboard API being implemented by a contributor, and the next release may fix your issue!

**Comment by theJayTea** [comment]
This may be fixed with v4. Could you please try it and let me know? Thanks

**Comment by arsaboo** [comment]
@theJayTea It now works in MS Word 🎉

**Comment by arsaboo** [comment]
@theJayTea Maybe I spoke too soon. It is still not quite reliable in MS Word. I still see the empty screen in Word:

![image](https://github.com/user-attachments/assets/6fec09e9-ec86-4184-916f-4fc09637b6c8)

**Comment by theJayTea** [comment]
Ah, bummer! I can try making the sleep timer a touch longer to ensure it reliably works.

**Comment by arsaboo** [comment]
@theJayTea Any update on the next build?

**Comment by theJayTea** [comment]
hi @arsaboo , I'm _super_ busy with my college applications until the 1st of November. I'll work on fixing bugs and adding feature requests after that :)
